### ISSUE TITLE
The result of # construct SCE containing logFCs for ea. cluster

### ISSUE THREAD

**Issue by Jungkooklove0901** [HelenaLC/muscat-comparison#5]
hello
At the Heatmap of cluster-wise logFCs step during Visualization

ref <- pbs$group_id == "Vehicle"
lfc <- lapply(assays(pbs), function(u) {
     y <- DGEList(u)
     y <- calcNormFactors(y)
     lcpm <- log1p(cpm.DGEList(y))
     lfc <- lcpm - rowMeans(lcpm[, ref])
     SingleCellExperiment(lfc,
         colData = colData(pbs),
         rowData = rowData(sce))
}) %>% do.call(what = cbind)
Here is the code, what value is y, the result of DGEList(u)?

**Comment by HelenaLC** [comment]
Not reproducible... I assume this is a bot as it's not the first issue of this type.
