### ISSUE TITLE
Heatmap of cluster-wise logFCs

### ISSUE THREAD

**Issue by Jungkooklove0901** [HelenaLC/muscat-comparison#6]
Visualization 
 # construct SCE containing logFCs for ea. cluster
 lfc <- lapply(assays(pbs), function(u) {
     y <- DGEList(u)
     y <- calcNormFactors(y)
     lcpm <- log1p(cpm.DGEList(y))
     lfc <- lcpm - rowMeans(lcpm[, ref])
     SingleCellExperiment(lfc,
         colData = colData(pbs),
         rowData = rowData(sce))
}) %>% do.call(what = cbind)

I did the following, but I got this error: In DGEList(u) : library size of zero detected.
How can I fix it?

**Comment by HelenaLC** [comment]
Not reproducible.
