### ISSUE TITLE
simData error :Trying to simulate more samples than available as reference; please set 'force = TRUE'.

### ISSUE THREAD

**Issue by ribatsua** [HelenaLC/muscat-comparison#7]
"When I tried to run the snakemake workflow, I encountered the following error: 'simData error: Trying to simulate more samples than available as reference; please set 'force = TRUE'.' After setting 'force = TRUE', the workflow ran successfully. However, the generated files were much larger in size than the corresponding files provided in the supplementary materials of the literature, and the 'results' folder had a size of 30GB."

**Comment by HelenaLC** [comment]
Not reproducible / understandable / more details required. Please reopen when you can provide a more comprehensive description of the issue, along with relevant code, snapshots etc.
