### ISSUE TITLE
Supplementary Figure 5

### ISSUE THREAD

**Issue by DarioS** [HelenaLC/muscat-comparison#9]
What proportion of genes is simulated in `FALSE` category and `TRUE` category? I can't pinpoint the code.

![image](https://github.com/user-attachments/assets/86d26f61-f30b-4dfe-8c5a-56b236b5b6e4)

**Comment by HelenaLC** [comment]
It's 10% DX (TRUE) for each category in each simulation. See scripts/sim_pars.R - the figure above pools results across all simulations and methods.
